### ISSUE TITLE
Formula

### ISSUE THREAD

**Issue by cevarief** [akeneo-labs/spreadsheet-parser#11]
Is there a way to show formula rather than value from createRowIterator ?

**Comment by jmleroux** [comment]
Hi @cevarief 

I think it's not in the scope of this parser, but i will study the question.

Regards,
JM

**Comment by jmleroux** [comment]
Hi @cevarief ,
I will not have the time to go further on this point.
But if you want to submit a PR, i will be pleased to read it.
