### ISSUE TITLE
XMLReader::open(): Unable to open source data

### ISSUE THREAD

**Issue by radu-ciobanu** [akeneo-labs/spreadsheet-parser#22]
Hi!

Your library is awesome!
I have a small problem though, maybe you can help:

I tested your sample code to parse an excel file and it works perfectly.
But when I try to do something like this:
```
function extractor_test($path) {
    $workbook = SpreadsheetParser::open($path);
    $worksheetIndex = $workbook->getWorksheetIndex('Sheet1');
    $iterator = $workbook->createRowIterator($worksheetIndex);

    return $iterator;
 }
foreach (extractor_test($filePath) as $key => $value) {
      $counter++;
}
```
I get this exception: XMLReader::open(): Unable to open source data'

**Comment by jmleroux** [comment]
Hi @radu-ciobanu ,

it probably comes from here : https://github.com/akeneo-labs/spreadsheet-parser/blob/master/src/Xlsx/AbstractXMLResource.php#L63

Are you sure of your ` $path` ?

**Comment by stof** [comment]
This is caused by #34 actually
