### ISSUE TITLE
the repository should have the Packagist hook configured

### ISSUE THREAD

**Issue by stof** [akeneo-labs/spreadsheet-parser#35]
Packagist does not reflect the merge of #33:
![akeneo_packagist](https://cloud.githubusercontent.com/assets/439401/14978947/9846e2e4-111f-11e6-89f6-bd9cf867eace.png)

It would be great to configure the Packagist hook on the repo (be careful that you need to configure the ``user`` field as the Packagist maintainer is ``akeneo``, not ``akeneo-labs``)

**Comment by stof** [comment]
@fitn please have a look at that. Your new 1.2.1 release is not on Packagist

**Comment by fitn** [comment]
@stof Seems good now ;)
Thank you for your feedback and thanks to @nidup for the changes
