### ISSUE TITLE
Multiple Sheets in Xls

### ISSUE THREAD

**Issue by gongalt** [akeneo-labs/spreadsheet-parser#41]
Hi,

I'd like to know if it's possible to parse multiple sheets in an excel file or does the spreadsheet parser only worked on a single worksheet file?

Thanks

**Comment by jmleroux** [comment]
The XLSX spreadsheet is able to read across multiple worksheets, and you can get them here: https://github.com/akeneo-labs/spreadsheet-parser/blob/master/src/Xlsx/Spreadsheet.php#L121

**Comment by gongalt** [comment]
Hi Thank you very much for pointing it out. Just what I needed. (Y)
