### ISSUE TITLE
reader does not start in first line

### ISSUE THREAD

**Issue by nblum** [akeneo-labs/spreadsheet-parser#45]
I try to read an xlsx file

```
        $workbook = \Akeneo\Component\SpreadsheetParser\SpreadsheetParser::open($file);
        $worksheets = $workbook->getWorksheets();
        $rowIterator = $workbook->createRowIterator($sheet);
        foreach ($rowIterator as $rowIndex => $values) {
```
but in some files the first row ist not the first in the document.

I can solve the problem by open the files with libreoffice an save them again.
Is there any solution by doing this programatically?

**Comment by jmleroux** [comment]
Hello @nblum ,
I'm not sure to understand the question.
Do you mean you want to know how to start reading rows from a specified line number?

**Comment by nblum** [comment]
Exactly, i need to Start always at the First row

**Comment by jesseteal** [comment]
I think this may be an issue of the first column of the first row is empty and therefore does not get read.  I'm running into a similar problem where sparse rows are skipped.
