### ISSUE TITLE
 RuntimeException  The file cannot be opened.

### ISSUE THREAD

**Issue by onnyprima** [akeneo-labs/spreadsheet-parser#60]
Writer using PhpOffice\PhpSpreadsheet\Writer\Xlsx while want to open file i got this error, 

(1/1)                                     RuntimeException                                                                  The file  cannot be opened.
--
in Psr17Factory.php line 44
at Psr17Factory->createStreamFromFile('')in PsrHttpFactory.php line 115
at PsrHttpFactory->createUploadedFile(object(UploadedFile))in PsrHttpFactory.php line 95
at PsrHttpFactory->getFiles(array('file' => object(UploadedFile)))in PsrHttpFactory.php line 65
at PsrHttpFactory->createRequest(object(Request))in JsonApiFactory.php line 27
at JsonApiFactory->create()in getJsonApiService.php line 12

**Comment by acrossoffwest** [comment]
> Writer using PhpOffice\PhpSpreadsheet\Writer\Xlsx while want to open file i got this error,
> 
> ## (1/1) RuntimeException The file cannot be opened.
> in Psr17Factory.php line 44
> at Psr17Factory->createStreamFromFile('')in PsrHttpFactory.php line 115
> at PsrHttpFactory->createUploadedFile(object(UploadedFile))in PsrHttpFactory.php line 95
> at PsrHttpFactory->getFiles(array('file' => object(UploadedFile)))in PsrHttpFactory.php line 65
> at PsrHttpFactory->createRequest(object(Request))in JsonApiFactory.php line 27
> at JsonApiFactory->create()in getJsonApiService.php line 12

Did you resolve that issue?

**Comment by onnyprima** [comment]
There's some undefined index while reading data, i set isset to check index is exist (sorry my bad English 😁)
